# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:/Projects/opengl donut"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:/Projects/opengl donut"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:/Projects/opengl donut/CMakeFiles" "C:/Projects/opengl donut//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:/Projects/opengl donut/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named donut

# Build rule for target.
donut: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 donut
.PHONY : donut

# fast build rule for target.
donut/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/build
.PHONY : donut/fast

src/gfx/abo.obj: src/gfx/abo.cpp.obj
.PHONY : src/gfx/abo.obj

# target to build an object file
src/gfx/abo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/abo.cpp.obj
.PHONY : src/gfx/abo.cpp.obj

src/gfx/abo.i: src/gfx/abo.cpp.i
.PHONY : src/gfx/abo.i

# target to preprocess a source file
src/gfx/abo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/abo.cpp.i
.PHONY : src/gfx/abo.cpp.i

src/gfx/abo.s: src/gfx/abo.cpp.s
.PHONY : src/gfx/abo.s

# target to generate assembly for a file
src/gfx/abo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/abo.cpp.s
.PHONY : src/gfx/abo.cpp.s

src/gfx/camera.obj: src/gfx/camera.cpp.obj
.PHONY : src/gfx/camera.obj

# target to build an object file
src/gfx/camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/camera.cpp.obj
.PHONY : src/gfx/camera.cpp.obj

src/gfx/camera.i: src/gfx/camera.cpp.i
.PHONY : src/gfx/camera.i

# target to preprocess a source file
src/gfx/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/camera.cpp.i
.PHONY : src/gfx/camera.cpp.i

src/gfx/camera.s: src/gfx/camera.cpp.s
.PHONY : src/gfx/camera.s

# target to generate assembly for a file
src/gfx/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/camera.cpp.s
.PHONY : src/gfx/camera.cpp.s

src/gfx/renderer.obj: src/gfx/renderer.cpp.obj
.PHONY : src/gfx/renderer.obj

# target to build an object file
src/gfx/renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/renderer.cpp.obj
.PHONY : src/gfx/renderer.cpp.obj

src/gfx/renderer.i: src/gfx/renderer.cpp.i
.PHONY : src/gfx/renderer.i

# target to preprocess a source file
src/gfx/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/renderer.cpp.i
.PHONY : src/gfx/renderer.cpp.i

src/gfx/renderer.s: src/gfx/renderer.cpp.s
.PHONY : src/gfx/renderer.s

# target to generate assembly for a file
src/gfx/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/renderer.cpp.s
.PHONY : src/gfx/renderer.cpp.s

src/gfx/shader.obj: src/gfx/shader.cpp.obj
.PHONY : src/gfx/shader.obj

# target to build an object file
src/gfx/shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/shader.cpp.obj
.PHONY : src/gfx/shader.cpp.obj

src/gfx/shader.i: src/gfx/shader.cpp.i
.PHONY : src/gfx/shader.i

# target to preprocess a source file
src/gfx/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/shader.cpp.i
.PHONY : src/gfx/shader.cpp.i

src/gfx/shader.s: src/gfx/shader.cpp.s
.PHONY : src/gfx/shader.s

# target to generate assembly for a file
src/gfx/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/shader.cpp.s
.PHONY : src/gfx/shader.cpp.s

src/gfx/texture.obj: src/gfx/texture.cpp.obj
.PHONY : src/gfx/texture.obj

# target to build an object file
src/gfx/texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/texture.cpp.obj
.PHONY : src/gfx/texture.cpp.obj

src/gfx/texture.i: src/gfx/texture.cpp.i
.PHONY : src/gfx/texture.i

# target to preprocess a source file
src/gfx/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/texture.cpp.i
.PHONY : src/gfx/texture.cpp.i

src/gfx/texture.s: src/gfx/texture.cpp.s
.PHONY : src/gfx/texture.s

# target to generate assembly for a file
src/gfx/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/texture.cpp.s
.PHONY : src/gfx/texture.cpp.s

src/gfx/vao.obj: src/gfx/vao.cpp.obj
.PHONY : src/gfx/vao.obj

# target to build an object file
src/gfx/vao.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/vao.cpp.obj
.PHONY : src/gfx/vao.cpp.obj

src/gfx/vao.i: src/gfx/vao.cpp.i
.PHONY : src/gfx/vao.i

# target to preprocess a source file
src/gfx/vao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/vao.cpp.i
.PHONY : src/gfx/vao.cpp.i

src/gfx/vao.s: src/gfx/vao.cpp.s
.PHONY : src/gfx/vao.s

# target to generate assembly for a file
src/gfx/vao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/vao.cpp.s
.PHONY : src/gfx/vao.cpp.s

src/gfx/window.obj: src/gfx/window.cpp.obj
.PHONY : src/gfx/window.obj

# target to build an object file
src/gfx/window.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/window.cpp.obj
.PHONY : src/gfx/window.cpp.obj

src/gfx/window.i: src/gfx/window.cpp.i
.PHONY : src/gfx/window.i

# target to preprocess a source file
src/gfx/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/window.cpp.i
.PHONY : src/gfx/window.cpp.i

src/gfx/window.s: src/gfx/window.cpp.s
.PHONY : src/gfx/window.s

# target to generate assembly for a file
src/gfx/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/gfx/window.cpp.s
.PHONY : src/gfx/window.cpp.s

src/glad.obj: src/glad.c.obj
.PHONY : src/glad.obj

# target to build an object file
src/glad.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/glad.c.obj
.PHONY : src/glad.c.obj

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/handle_input.obj: src/handle_input.cpp.obj
.PHONY : src/handle_input.obj

# target to build an object file
src/handle_input.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/handle_input.cpp.obj
.PHONY : src/handle_input.cpp.obj

src/handle_input.i: src/handle_input.cpp.i
.PHONY : src/handle_input.i

# target to preprocess a source file
src/handle_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/handle_input.cpp.i
.PHONY : src/handle_input.cpp.i

src/handle_input.s: src/handle_input.cpp.s
.PHONY : src/handle_input.s

# target to generate assembly for a file
src/handle_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/handle_input.cpp.s
.PHONY : src/handle_input.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh/perlin.obj: src/mesh/perlin.cpp.obj
.PHONY : src/mesh/perlin.obj

# target to build an object file
src/mesh/perlin.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/mesh/perlin.cpp.obj
.PHONY : src/mesh/perlin.cpp.obj

src/mesh/perlin.i: src/mesh/perlin.cpp.i
.PHONY : src/mesh/perlin.i

# target to preprocess a source file
src/mesh/perlin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/mesh/perlin.cpp.i
.PHONY : src/mesh/perlin.cpp.i

src/mesh/perlin.s: src/mesh/perlin.cpp.s
.PHONY : src/mesh/perlin.s

# target to generate assembly for a file
src/mesh/perlin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/mesh/perlin.cpp.s
.PHONY : src/mesh/perlin.cpp.s

src/mesh/perlin_mesh.obj: src/mesh/perlin_mesh.cpp.obj
.PHONY : src/mesh/perlin_mesh.obj

# target to build an object file
src/mesh/perlin_mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/mesh/perlin_mesh.cpp.obj
.PHONY : src/mesh/perlin_mesh.cpp.obj

src/mesh/perlin_mesh.i: src/mesh/perlin_mesh.cpp.i
.PHONY : src/mesh/perlin_mesh.i

# target to preprocess a source file
src/mesh/perlin_mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/mesh/perlin_mesh.cpp.i
.PHONY : src/mesh/perlin_mesh.cpp.i

src/mesh/perlin_mesh.s: src/mesh/perlin_mesh.cpp.s
.PHONY : src/mesh/perlin_mesh.s

# target to generate assembly for a file
src/mesh/perlin_mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/donut.dir/build.make CMakeFiles/donut.dir/src/mesh/perlin_mesh.cpp.s
.PHONY : src/mesh/perlin_mesh.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... donut"
	@echo "... src/gfx/abo.obj"
	@echo "... src/gfx/abo.i"
	@echo "... src/gfx/abo.s"
	@echo "... src/gfx/camera.obj"
	@echo "... src/gfx/camera.i"
	@echo "... src/gfx/camera.s"
	@echo "... src/gfx/renderer.obj"
	@echo "... src/gfx/renderer.i"
	@echo "... src/gfx/renderer.s"
	@echo "... src/gfx/shader.obj"
	@echo "... src/gfx/shader.i"
	@echo "... src/gfx/shader.s"
	@echo "... src/gfx/texture.obj"
	@echo "... src/gfx/texture.i"
	@echo "... src/gfx/texture.s"
	@echo "... src/gfx/vao.obj"
	@echo "... src/gfx/vao.i"
	@echo "... src/gfx/vao.s"
	@echo "... src/gfx/window.obj"
	@echo "... src/gfx/window.i"
	@echo "... src/gfx/window.s"
	@echo "... src/glad.obj"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/handle_input.obj"
	@echo "... src/handle_input.i"
	@echo "... src/handle_input.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh/perlin.obj"
	@echo "... src/mesh/perlin.i"
	@echo "... src/mesh/perlin.s"
	@echo "... src/mesh/perlin_mesh.obj"
	@echo "... src/mesh/perlin_mesh.i"
	@echo "... src/mesh/perlin_mesh.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

